### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by superlolo95** [genius-crm/Template-responsive#13]
Hello,
I just installed the template and I have an issue.
This is a very good job and the responsiness is well working.

However, apprently, the pages are trying to load a css without success. The display seems ok but I have this missing fiel error on every load page.
libraries/dist/css/AdminLTE.min.css is not found
Could anyone help me on that point?

Regards

**Comment by barra** [comment]
hi, try to remove this line: https://github.com/genius-crm/Template-responsive/blob/8d6f69d61c992d33432d4a58ecf95f1b2fd8b7a7/vlayout2/modules/Vtiger/Header.tpl#L27

AdminLTE.min.css was not necessary.

**Comment by superlolo95** [comment]
Dear,
Thanks,
Effectivly it was the below lines to be removed.



```
    <link href="libraries/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
```

in vlayout2\modules\Vtiger\Header.tpl

Thanks for the quick fix.
