### ISSUE TITLE
ricerca globale

### ISSUE THREAD

**Issue by simonetravaglini** [genius-crm/Template-responsive#8]
La picklist della ricerca globale è compressa:
![image](https://cloud.githubusercontent.com/assets/6990139/11528030/8c2a6b56-98e4-11e5-8391-7a8caa30d94d.png)

**Comment by barra** [comment]
Ho indicato a Giorgio qualche giorno fa:

aggiungi

.chosen-container {width: 160px !important;}

allo style.css

2015-12-02 11:05 GMT+01:00 simonetravaglini notifications@github.com:
